import "./globals.css";
import ClientLayoutWrapper from "./components/ClientLayoutWrapper";
import Footer from "./components/Footer";
import { Bellefair } from "next/font/google";
import NavBar from "./components/NavBar";
import NavBar2 from "./components/NavBar2";
import RouteLoader from "./components/RouteLoader";

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bellefair", // Define CSS variable
});

export const metadata = {
  title: "Aureon",
  icon:'/icon.png',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head><meta name="viewport" content="width=device-width, initial-scale=1.0"/></head>
      <body className={bellefair.variable}>
      <ClientLayoutWrapper>
       <NavBar/>
       <RouteLoader/>
       {/* <NavBar2/> */}
        {children}
        <Footer/>
      </ClientLayoutWrapper>
      </body>
    </html>
  );
}
